---
- name: Create owner
  user:
    name: "{{ am_owner }}"
    shell: /bin/bash
    system: true

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ am_owner }}"
    group: "{{ am_group }}"
    mode: 0755
  with_items: "{{ am_amster_directories }}"
  when: am_amster_directories|default(False)

- name: Amster script
  stat:
    path: "{{ amster_home_version }}/amster"
  register: amster_script

- block:
  - name: Download zip file
    get_url:
      url: "{{ amster_versions[amster_version]['url'] }}"
      dest: "/tmp/{{ amster_versions[amster_version]['url']|basename }}"
      checksum: "{{ amster_versions[amster_version]['checksum'] }}"
      timeout: 600
      mode: 1373
    register: get_url_result
    until: get_url_result is succeeded

  - name: Unzip the zipfile
    unarchive:
      dest:  "{{ amster_home_version }}"
      owner: "{{ am_owner }}"
      group: "{{ am_group }}"
      remote_src: yes
      src: "/tmp/{{ amster_versions[amster_version]['url']|basename }}"
  when: not amster_script.stat.exists

- name: Create home link
  file:
   src: "{{ amster_home_version }}"
   dest: "{{ amster_home_link }}"
   state: link
