---
- name: Create owner
  user:
    name: "{{ amster_owner }}"
    shell: /bin/bash
    system: true

- name: Create home
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ amster_owner }}"
    group: "{{ amster_group }}"
    mode: 0755
  with_items: "{{ am_config_directories }}"
  when: am_config_directories|default(False)

- name: Download zip file
  get_url:
    url: "{{ amster_versions[amster_version]['url'] }}"
    dest: "{{ amster_download_dir }}/{{ amster_versions[amster_version]['url']|basename }}"
    checksum: "{{ amster_versions[amster_version]['checksum'] }}"
    timeout: 600
    mode: 1373
  register: get_url_result
  until: get_url_result is succeeded

- name: Unzip the zipfile
  unarchive:
    dest:  "{{ amster_home_version }}"
    owner: "{{ amster_owner }}"
    group: "{{ amster_group }}"
    remote_src: yes
    src: "{{ amster_download_dir }}/{{ amster_versions[amster_version]['url']|basename }}"

- name: Create home link
  file:
   src: "{{ amster_home_version }}"
   dest: "{{ amster_home_link }}"
   state: link
