---
- name: Shared secrets
  file:
    path: "{{ am_shared_secrets  }}"
    state: directory
    mode: 0700

- name: AM cert
  copy:
    content: "{{ am_certificate[item]['cert'] }}"
    dest: "{{ am_shared_secrets }}/{{ item }}.crt"
    mode: '600'
  register: am_c

- name: AM key
  copy:
    content: "{{ am_certificate[item]['key'] }}"
    dest: "{{ am_shared_secrets }}/{{ item }}.key"
    mode: '600'
  register: am_k

- debug:
    msg: |
     am_k: {{ am_k }}
     am_c: {{ am_c }}

- block:
  - name: Get password
    ansible.builtin.slurp:
      src: "{{ am_certificate[item]['keystore_pass_file'] }}"
    register: keystore_password

  - name: Create AM p12
    shell:
      cmd: >
        openssl pkcs12 -export
        -in {{ am_shared_secrets }}/{{ item }}.crt
        -inkey {{ am_shared_secrets }}/{{ item }}.key
        -out {{ am_shared_secrets }}/{{ item }}.p12
        -name {{ am_certificate[item]['name']|default(item) }}
        -password 'pass:{{ keystore_password['content']|b64decode }}'

  - name: Remove certificate
    java_cert:
      cert_alias: "{{ am_certificate[item]['name']|default(item) }}"
      #cert_path: "{{ item['path'] }}" # required but not sure why
      pkcs12_path: "{{ am_shared_secrets }}/{{ item }}.p12"
      keystore_path: "{{ am_certificate[item]['keystore_path'] }}"
      keystore_pass: "{{ keystore_password['content']|b64decode }}"
      keystore_type: JCEKS
      executable: "{{ am_certificate[item]['keytool'] }}"
      state: absent
    ignore_errors: yes # might not exist

  - name: Add certificate
    java_cert:
      pkcs12_path: "{{ am_shared_secrets }}/{{ item }}.p12"
      pkcs12_alias: "{{ am_certificate[item]['name']|default(item) }}"
      pkcs12_password: "{{ keystore_password['content']|b64decode }}"
      cert_alias: "{{ am_certificate[item]['name']|default(item) }}"
      #cert_path: "{{ item['path'] }}"
      keystore_path: "{{ am_certificate[item]['keystore_path'] }}"
      keystore_pass: "{{ keystore_password['content']|b64decode }}"
      keystore_type: JCEKS
      executable: "{{ am_certificate[item]['keytool'] }}"
      state: present
    notify: restart tomcat instance
  when: am_c.changed or am_k.changed
