---
# AM won't start without home directory
- name: Create home directory for tomcat
  file:
    path: /home/tomcat
    state: directory
    owner: tomcat
    group: tomcat
    mode: 0755

- name: Download AM war, put it in Tomcat webapps directory.
# Note the new specs: this is all, we do not do anything with the war outside of Tomcat
  get_url:
    url: "{{ am_versions[am_version]['url'] }}"
    checksum: "{{ am_versions[am_version]['checksum'] }}"
    dest: "{{ tomcat_home_version }}/webapps/am.war"
    mode: "755"
  notify: restart tomcat instance

