---
- name: Keystore cache file
  get_url:
    url: "{{ am_keystore['url'] }}"
    dest: "{{ amster_am_install['cfgDir'] }}/{{ am_context }}/{{ am_keystore['basename']|default(am_keystore['url']|
    basename) }}.cache"
    checksum: "{{ am_keystore['checksum']|default(omit) }}"
    group: "{{ am_keystore['group']|default('tomcat') }}"
    owner: "{{ am_keystore['owner']|default('tomcat') }}"
    backup: "{{ am_keystore['backup']|default(True) }}"
    mode: "640"
  notify: "{{ am_keystore['notify']|default(omit) }}"
  register: keystore_cache_file

- block:
  - name: Download keystore
    get_url:
      url: "{{ am_keystore['url'] }}"
      dest: "{{ amster_am_install['cfgDir'] }}/{{ am_context }}/{{ am_keystore['basename']|default(am_keystore['url']|
      basename) }}"
      checksum: "{{ am_keystore['checksum']|default(omit) }}"
      group: "{{ am_keystore['group']|default('tomcat') }}"
      owner: "{{ am_keystore['owner']|default('tomcat') }}"
      backup: "{{ am_keystore['backup']|default(True) }}"
      mode: "640"
    notify: "{{ am_keystore['notify']|default(omit) }}"

  - name: Set / update storepass
    copy:
      content: "{{ am_keystore['storepass']|default('changeit') }}"
      dest: "{{ amster_am_install['cfgDir'] }}/{{ am_context }}/.storepass"
      group: "{{ am_keystore['group']|default('tomcat') }}"
      owner: "{{ am_keystore['owner']|default('tomcat') }}"
      backup: "{{ am_keystore['backup']|default(True) }}"
      mode: "640"
  when: keystore_cache_file.changed
