---
- name: Create owner
  user:
    name: "{{ am_owner }}"
    shell: /bin/bash
    system: true

- name: Create home
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ am_owner }}"
    group: "{{ am_group }}"
    mode: 0755
  with_items:
    - "{{ am_home }}"
    - "{{ am_home }}/{{ am_version }}"


- include: install.yml

- name: Home link
# Will create a symlink, allowing e.g. splunk to expect the logfile in /opt/am/am/openamcfg/am/log
# and not a directory name with a version in it.
  file:
   src: "{{ am_home }}/{{ am_version }}"
   dest: "{{ am_home_link }}"
   state: link

- name: Block for non-root splunk user setup; only to be run for Vagrant DE as for Equinix it's in the Infra Ansible

  block:
    - name: Add nix splunk group
      group:
        name:  splunk
        state: present
      become: yes

    - name: Add nix splunk user
      user:
        name: splunk
        groups: splunk
        home: /opt/splunk
        state: present
        shell: /bin/bash
#        password: "{{ lookup('password', '/dev/null length=32') | password_hash('sha512')"
# Copypaste from JanH, gives syntax error?
      become: yes