---
- name: Download war file
  get_url:
    url: "{{ openam_versions[openam_version]['url'] }}"
    dest: "{{ openam_home }}/{{ openam_version }}/downloads/{{ openam_versions[openam_version]['url']|basename }}"
    checksum: "{{ openam_versions[openam_version]['checksum'] }}"
    timeout: 600
    mode: 1373
    owner: "{{ am_owner }}"
    group: "{{ am_group }}"
  register: get_url_result
  until: get_url_result is succeeded
