---
opends_version: 6.5.4
opends_home: /opt/ds

ds_owner: forgerock
ds_group: forgerock

ds_packages: []

# ForgeRock downloads cannot be downloaded automatically
# So override ds_versions in a group_vars / host_vars file
ds_versions:
  6.5.4:
    url: https://backstage.forgerock.com/downloads/
    checksum: "sha256: 820a197f4ac11b020c653ef00c684e63034df1f9f591b826ee4735c4bde7b8f1"

opends_versions_sequence: [6.5.4]
opends_hostname: fr1.example.com
# Probably overwritten in the group_vars for a specific play, eg. with a nip.io adress

opends_setup_config:
  rootUserDN: '"cn=Directory Manager"'
  rootUserPassword: FRdemo123
  monitorUserPassword: FRdemo123
  hostname: "{{ opends_hostname }}"
  ldapPort: 3389
  ldapsPort: 3636
  adminConnectorPort: 34444
  profile: am-config
  set: am-config/amConfigAdminPassword:FRdemo123
  acceptLicense: ""
  
  
# There extra fields are in the specs-docoument in case of PRD.  Simply add them to the config string by uncommenting when needed.
# --productionMode 
# --httpPort 38081 
# --httpsPort 38443 


opends_setup_user:
  rootUserDN: '"cn=Directory Manager"'
  rootUserPassword: FRdemo123
  hostname: "{{ opends_hostname }}"
  ldapPort: 4389
  ldapsPort: 4636
  adminConnectorPort: 44444
  baseDN: dc=example,dc=com 
  acceptLicense: ""
  
  
