---
ds_version: 6.5.4
ds_home: /opt/ds

ds_owner: forgerock
ds_group: forgerock
ds_rootpwd: 4NnJLdVq9oxqUcVixWP4 
ds_packages: []

# ForgeRock downloads cannot be downloaded automatically
# So override ds_versions in a group_vars / host_vars file (on DEV a local cache, from BTO onwards a BKWI git location)
ds_versions:
  6.5.4:
    url: https://backstage.forgerock.com/downloads/
    checksum: "sha256: 820a197f4ac11b020c653ef00c684e63034df1f9f591b826ee4735c4bde7b8f1"

ds_versions_sequence: [6.5.4]
ds_hostname: fr1.example.com
# Probably overwritten in the group_vars for a specific play, eg. with a nip.io adress

ds_setup_config:
  instancePath:  "{{ ds_home }}/{{ ds_home|basename }}-{{ ds_version }}"
  rootUserDn: '"cn=Directory Manager"'
  rootUserPassword: "{{ ds_rootpw }}"
  hostname: "{{ ds_hostname }}"
  adminConnectorPort: 4444
  ldapPort: 10389
  enableStartTls: ""
  productionMode: ""
  ldapsPort: 10636
  profile: am-config:6.5
  set: "am-config/amConfigAdminPasswor:{{ ds_rootpwd }}" 
  acceptLicense: ""


dsconf_cert:
  handler-name: LDAPS 
  add: ssl-cert-nickname:config-server-cert
  hostname: "{{ ds_hostname }}"
  port: 4444
  bindDN: '"cn=Directory Manager"' 
  bindPassword: "{{ ds_rootpw }}  "
  trustAll: ""
  no-prompt: ""


dsc_conf_look:
  hostname: "{{ ds_hostname }}"
  port: 4444
  bindDN:  '"cn=Directory Manager"' 
  bindPassword: "{{ ds_rootpw }}  "
  trustAll: ""
  no-prompt: ""
  set: 'lookthrough-limit:20000'   
  
 
dsc_conf_smtp:
  hostname: "{{ ds_hostname }}"
  port: 4444
  bindDN:  '"cn=Directory Manager"' 
  bindPassword: "{{ ds_rootpw }}  "
  trustAll: ""
  no-prompt: ""
  set: 'smtp-server:127.0.0.1:25'

dsc_connect_LDAP:
  handler-name: LDAP
  hostname: "{{ ds_hostname }}"
  port: 4444
  bindDN:  '"cn=Directory Manager"' 
  bindPassword: "{{ ds_rootpw }}  "
  trustAll: ""
  no-prompt: ""
  set: 'enabled:false' 


dsc_connect_LDAPS:
  handler-name: LDAPS
  hostname: "{{ ds_hostname }}"
  port: 4444
  bindDN:  '"cn=Directory Manager"' 
  bindPassword: "{{ ds_rootpw }}  "
  trustAll: ""
  no-prompt: ""
  set: 'allow-ldap-v2:true'


dsc_logger_file:
  publisher-name: '"File-Based Access Logger"'
  hostname: "{{ ds_hostname }}"
  port: 4444
  bindDN:  '"cn=Directory Manager"' 
  bindPassword: "{{ ds_rootpw }}  "
  trustAll: ""
  no-prompt: ""
  set: 'enabled:false' 


dsc_logger_test:
  publisher-name: '"File-Based Access Logger"'
  hostname: "{{ ds_hostname }}"
  port: 4444
  bindDN:  '"cn=Directory Manager"' 
  bindPassword: "{{ ds_rootpw }}  "
  trustAll: ""
  no-prompt: ""
  set: 'enabled:false'
  set: 'Testvalue'

dsc_pol_default_inquire:
  port: 10636
  bindDN: '"cn=Directory Manager"' 
  bindPassword: "{{ ds_rootpw }}  "
  trustAll: ""
  no-prompt: ""
  policy-name: '"Default Password Policy"' 






