---
ds_version: 6.5.4
ds_home: /opt/ds
ds_home_version: "{{ ds_home  }}/{{ ds_home|basename }}-{{ ds_version }}"
ds_home_link: "{{ ds_home  }}/{{ ds_home|basename }}"
ds_java_home: "{{ java['version']|c2platform.core.java_home }}"

ds_owner: forgerock
ds_group: forgerock
ds_rootpw:  supersecret
ds_replication_global_admin: admin
ds_replication_global_admin_password: supersecret # Su12perSec34retIt5Is
# Note: requires a "good" password e.g Su12perSec34retIt5Is
#       see vault
ds_replication_port: 8989
ds_replication_enable: no
ds_import_enable: no
ds_db_schema_ldifs_enable: no
ds_packages: []

ds_versions:
  6.5.4:
    url: https://backstage.forgerock.com/downloads/
    checksum: "sha256: 820a197f4ac11b020c653ef00c684e63034df1f9f591b826ee4735c4bde7b8f1"
  4.4.10:
    url: https://github.com/OpenIdentityPlatform/OpenDJ/releases/download/4.4.10/opendj-4.4.10.zip
    checksum: "sha256: 6c608d4ff8234401b1b5baf1fd7cfc9b56128dc7ec3f657cdce441df94f6d434"

ds_versions_sequence: [6.5.4]
ds_hostname: "{{ ansible_fqdn }}"

ds_connect:
  hostname: "{{ ds_hostname }}"
  port: 4444
  bindDN:  cn=Directory Manager
  bindPassword: "{{ ds_rootpw }}"
  trustAll: ""
  no-prompt: ""

ds_connect_ssl: '{{ ds_connect|combine({"useSsl":""}) }}'
