---
ds_version: 6.5.4
ds_home: /opt/ds
ds_home_version: "{{ ds_home  }}/{{ ds_home|basename }}-{{ ds_version }}"
ds_home_link: "{{ ds_home  }}/{{ ds_home|basename }}"

ds_owner: forgerock
ds_group: forgerock
ds_rootpw:  supersecret
ds_replication_global_admin: admin
ds_replication_global_admin_password: supersecret # requires better password e.g Su12perSec34retIt5Is
ds_replication_port: 8989
ds_replication_enable: no
ds_import_enable: no
ds_db_schema_ldifs_enable: no
ds_packages: []

# ForgeRock downloads cannot be downloaded automatically
# So override ds_versions in a group_vars / host_vars file (on DEV a local cache, from BTO onwards a BKWI git location)
ds_versions:
  6.5.4:
    url: https://backstage.forgerock.com/downloads/
    checksum: "sha256: 820a197f4ac11b020c653ef00c684e63034df1f9f591b826ee4735c4bde7b8f1"
  4.4.10:
    url: https://github.com/OpenIdentityPlatform/OpenDJ/releases/download/4.4.10/opendj-4.4.10.zip
    checksum: "sha256: 6c608d4ff8234401b1b5baf1fd7cfc9b56128dc7ec3f657cdce441df94f6d434"

ds_versions_sequence: [6.5.4]
ds_hostname: "{{ ansible_fqdn }}"

ds_connect:
  hostname: "{{ ds_hostname }}"
  port: 4444
  bindDN:  cn=Directory Manager
  bindPassword: "{{ ds_rootpw }}"
  trustAll: ""
  no-prompt: ""

ds_connect_ssl: '{{ ds_connect|combine({"useSsl":""}) }}'

ds_setup_config:
  instancePath:  "{{ ds_home_version }}"
  rootUserDN: '"cn=Directory Manager"'
  rootUserPassword: "{{ ds_rootpw }}"
  hostname: "{{ ds_hostname }}"
  adminConnectorPort: 4444
  ldapPort: 10389
  enableStartTls: ""
  productionMode: ""
  ldapsPort: 10636
  profile: am-config:6.5
  set: "am-config/amConfigAdminPassword:{{ ds_rootpw }}"
  acceptLicense: ""

ds_config_backend_index_templates:
  uid_etc:
    backend-name: suwiRoot
    set:
      - index-type:equality
      - index-entry-limit:4000
  cn_etc:
    backend-name: suwiRoot
    set:
      - index-type:equality
      - set index-type:substring
      - index-entry-limit:4000

# Password policy settings
ds_config_pps:
  generic:
    - default-password-storage-scheme:Salted SHA-512
    - password-attribute:userPassword
    - deprecated-password-storage-scheme:Salted SHA-1
    - last-login-time-attribute:ds-pwp-last-login-time
    - last-login-time-format:yyyyMMddHHmmss
    - password-expiration-warning-interval:7 days
    - min-password-age:24 hours
    - password-change-requires-current-password:true
    - password-history-duration:0 seconds
    - skip-validation-for-administrators:true
    - require-secure-authentication:true
  default:
    - allow-user-password-changes:true
    - expire-passwords-without-warning:true
    - grace-login-count:2
    - lockout-duration:0 minutes
    - lockout-failure-expiration-interval:0 minutes
    - lockout-failure-count:5
    - max-password-reset-age:14 days
    - password-history-count:10
    - require-secure-password-changes:true
    - max-password-age:56 days
    - force-change-on-add:true
    - force-change-on-reset:true
    - idle-lockout-interval:45 days
  service-accounts:
    - expire-passwords-without-warning:false
    - force-change-on-add:false
    - force-change-on-reset:false
    - grace-login-count:10
    - idle-lockout-interval:2000 days
    - lockout-duration:1 s
    - lockout-failure-expiration-interval:1 s
    - lockout-failure-count:10000
    - max-password-age:2000 days
    - max-password-reset-age:8 hours
    - password-history-count:5
    - require-secure-password-changes:true
  jmx:
    - default-password-storage-scheme:Salted SHA-512
    - expire-passwords-without-warning:false
    - force-change-on-add:false
    - force-change-on-reset:false
    - grace-login-count:10
    - idle-lockout-interval:2000 days
    - lockout-duration:480 s
    - lockout-failure-expiration-interval:600 s
    - lockout-failure-count:5
    - max-password-age:2000 days
    - max-password-reset-age:8 hours
    - password-history-count:5
    - password-history-duration:0 seconds

ds_config:
  connection-handler_set_cert: # note underscore → connection-handler component
    - handler-name: LDAPS
      add: ssl-cert-nickname:config-server-cert
  connection-handler:
    - handler-name: LDAP
      set: enabled:false
    - handler-name: LDAPS
      set: allow-ldap-v2:true
  global-configuration:
    - set: lookthrough-limit:20000
    - set: smtp-server:127.0.0.1:25
  log-publisher:
    - publisher-name: File-Based Access Logger
      set: enabled:false
  password-policy_create:
    - policy-name: Default Password Policy
      type: password-policy
      set:
        - default-password-storage-scheme:Salted SHA-512
        - password-attribute:userPassword
      when:
        regex: '^(Default Password Policy)\s+:'
        method: list-password-policies
        match: no
        #switches:
        #  property: password-attribute
  password-policy:
    - policy-name: Default Password Policy
      set: "{{ ds_config_pps['generic'] + ds_config_pps['default'] }}"
      add:
        - password-validator:Length-Based Password Validator
        - password-validator:Similarity-Based Password Validator
        - password-validator:Attribute Value
        - password-validator:Unique Characters
        - password-validator:Character Set
  password-policy_remove:
    - policy-name: Default Password Policy
      remove: password-validator:At least 8 characters
      when:
        regex: '^password-validator\s:[\S\s.]*(\sAt least 8 characters)[\s,].*$'
        method: get-password-policy-prop
        match: yes
        switches:
           policy-name: Default Password Policy
           property: password-validator
    - policy-name: Default Password Policy
      remove: password-validator:Common passwords
      when:
        regex: '^password-validator\s:[\S\s.]*(\sCommon passwords)[\s,].*$'
        method: get-password-policy-prop
        match: yes
        switches:
           policy-name: Default Password Policy
           property: password-validator
    - policy-name: Default Password Policy
      remove: password-validator:Dictionary
      when:
        regex: '^password-validator\s:[\S\s.]*(\sDictionary)[\s,].*$'
        method: get-password-policy-prop
        match: yes
        switches:
           policy-name: Default Password Policy
           property: password-validator
    - policy-name: Default Password Policy
      remove: password-validator:Repeated Characters
      when:
        regex: '^password-validator\s:[\S\s.]*(\sRepeated Characters)[\s,].*$'
        method: get-password-policy-prop
        match: yes
        switches:
           policy-name: Default Password Policy
           property: password-validator
  password-policy_service-accounts-create:
    - policy-name: Password Policy Service Accounts
      type: password-policy
      set:
        - default-password-storage-scheme:Salted SHA-512
        - password-attribute:userPassword
  password-policy_service-accounts:
    - policy-name: Password Policy Service Accounts
      set: "{{ ds_config_pps['generic'] + ds_config_pps['service-accounts'] }}"
  password-policy_service-accounts-jmx-create:
    - policy-name: Password Policy JMX Service Accounts
      type: password-policy
      set:
        - default-password-storage-scheme:Salted SHA-512
        - password-attribute:userPassword
  password-policy_service-accounts-jmx:
    - policy-name: Password Policy JMX Service Accounts
      set: "{{ ds_config_pps['generic'] + ds_config_pps['jmx'] }}"
  password-validator:
    - validator-name: '"Length-Based Password Validator"'
      set:
        - enabled:true
        - min-password-length:8
        - max-password-length:0
    - validator-name: '"Similarity-Based Password Validator"'
      set:
        - enabled:true
        - min-password-difference:3
    - validator-name: '"Attribute Value"'
      set: enabled:true
      add:
        - match-attribute:cn
        - match-attribute:sn
        - match-attribute:givenName
        - match-attribute:uid
    - validator-name: '"Unique Characters"'
      set:
        - enabled:true
        - min-unique-characters:4
        - case-sensitive-validation:true
    - validator-name: '"Character Set"'
      set:
        - enabled:true
        - allow-unclassified-characters:true
  backend_create:
    - set:
        - base-dn:c=NL
        - enabled:true
        - db-cache-percent:5
      type: je
      backend-name: suwiRoot
    - set:
        - base-dn:dc=bkwi,dc=nl
        - enabled:true
        - db-cache-percent:5
      type: je
      backend-name: userRoot
  access-control-handler:
    - add:
        - global-aci:"(targetcontrol=\"2.16.840.1.113730.3.4.18\") (version 3.0; acl \"Authenticated users control access\"; allow(read) userdn=\"ldap:///all\";)" 
        - global-aci:"(targetcontrol=\"1.3.6.1.1.12 || 1.3.6.1.1.13.1 || 1.3.6.1.1.13.2 || 1.2.840.113556.1.4.319 || 1.2.826.0.1.3344810.2.3 || 2.16.840.1.113730.3.4.18 || 2.16.840.1.113730.3.4.9 || 1.2.840.113556.1.4.473 || 1.3.6.1.4.1.42.2.27.9.5.9\") (version 3.0; acl \"and the rest\"; allow(read) userdn=\"ldap:///all\";)"
        - global-aci:"(targetattr!=\"userPassword||authPassword||changes||changeNumber||changeType||changeTime||targetDN||newRDN||newSuperior||deleteOldRDN||targetEntryUUID||targetUniqueID||changeInitiatorsName||changeLogCookie\")(version 3.0; acl \"Anonymous read access\"; allow (read,search,compare) userdn=\"ldap:///dc=bkwi,dc=nl\";)"
  backend-index_create:
    - "{{ ds_config_backend_index_templates['uid_etc']|combine({ 'index-name: 'uid' }) }}"
    - "{{ ds_config_backend_index_templates['uid_etc']|combine({ 'index-name':'member' }) }}"
    - "{{ ds_config_backend_index_templates['uid_etc']|combine({ 'index-name':'uniqueMember' }) }}"
    - "{{ ds_config_backend_index_templates['uid_etc']|combine({ 'index-name':'ou' }) }}"
    - "{{ ds_config_backend_index_templates['cn_etc']|combine({ 'index-name':'cn' }) }}"
    - "{{ ds_config_backend_index_templates['cn_etc']|combine({ 'index-name':'givenName' }) }}"
    - "{{ ds_config_backend_index_templates['cn_etc']|combine({ 'index-name':'sn' }) }}"
    - "{{ ds_config_backend_index_templates['cn_etc']|combine({ 'index-name':'mail' }) }}"
    - set:
        - index-type:equality
        - index-type:substring
        - index-entry-limit:100000
      backend-name: suwiRoot
      index-name: businessCategory
#  password-validator_add:
#    - validator-name: '"Attribute Value"'
#      set: enabled:true
#      add:
#        - match-attribute:cn
#        - match-attribute:sn
#        - match-attribute:givenName
#        - match-attribute:uid
#      #remove:
#      #  - match-attribute:sn

ds_config_components:
  - connection-handler
  - global-configuration
  - log-publisher
  - password-policy_create
  - password-policy
  - password-policy_service-accounts-create
  - password-policy_service-accounts
  - password-policy_service-accounts-jmx-create
  - password-policy_service-accounts-jmx
  - password-validator
  - password-policy_remove
  - backend_create
  - backend-index_create
  - access-control-handler
  #- password-validator_add

# Components that require use of a fingerpint to detect
# changes between current and desired state
ds_config_components_fingerprint:
  - connection-handler
  #- password-validator_add
  #- password-policy_create
  - password-policy
  - password-policy_service-accounts-create
  - password-policy_service-accounts
  - password-policy_service-accounts-jmx-create
  - password-policy_service-accounts-jmx
  - backend_create
  - backend-index_create
  - access-control-handler


