---
ds_version: 6.5.4
ds_home: /opt/ds

ds_owner: forgerock
ds_group: forgerock
ds_rootpw: supersecure
ds_replication_global_admin: admin
ds_replication_global_admin_password: supersecure
ds_packages: []

# ForgeRock downloads cannot be downloaded automatically
# So override ds_versions in a group_vars / host_vars file (on DEV a local cache, from BTO onwards a BKWI git location)
ds_versions:
  6.5.4:
    url: https://backstage.forgerock.com/downloads/
    checksum: "sha256: 820a197f4ac11b020c653ef00c684e63034df1f9f591b826ee4735c4bde7b8f1"

ds_versions_sequence: [6.5.4]
ds_hostname: "{{ ansible_hostname }}"

# ds_db_schema_ldifs:
#  appPerson: | # /opt/ds/ds-6.5.4/db/schema/appPerson.ldif
#    dn: cn=schema
#    changetype: modify
#    add: attributeTypes
#    attributeTypes: ( app-account-expiration-time-oid NAME 'app-account-expiration-time' DESC 'The time the account becomes disabled' EQUALITY generalizedTimeMatch ORDERING generalizedTimeOrderingMatch SUBSTR caseIgnoreSubstringsMatch SYNTAX 1.3.6.1.4.1.1466.115.121.1.24 SINGLE-VALUE USAGE userApplications )
#    dn: cn=schema
#    changetype: modify
#    add: objectClasses
#    objectClasses: ( AppPerson-oid NAME 'appPerson' DESC 'Extra properties for a app user' SUP top AUXILIARY MAY ( app-account-expiration-time ) )

ds_connect:
  hostname: "{{ ds_hostname }}"
  port: 4444
  bindDN:  cn=Directory Manager
  bindPassword: "{{ ds_rootpw }}"
  trustAll: ""
  no-prompt: ""

ds_setup_config:
  instancePath:  "{{ ds_home }}/{{ ds_home|basename }}-{{ ds_version }}"
  rootUserDN: '"cn=Directory Manager"'
  rootUserPassword: "{{ ds_rootpw }}"
  hostname: "{{ ds_hostname }}"
  adminConnectorPort: 4444
  ldapPort: 10389
  enableStartTls: ""
  productionMode: ""
  ldapsPort: 10636
  profile: am-config:6.5
  set: "am-config/amConfigAdminPassword:{{ ds_rootpw }}"
  acceptLicense: ""

dsc_ustore_sroot_inquire:
  hostname: "{{ ds_hostname }}"
  port: 4444
  bindDN:  '"cn=Directory Manager"'
  bindPassword: "{{ ds_rootpw }}"
  trustAll: ""
  useSsl: ""
  baseDn: '"c=NL"'

dsc_ustore_uroot_inquire:
  hostname: "{{ ds_hostname }}"
  port: 4444
  bindDN:  '"cn=Directory Manager"'
  bindPassword: "{{ ds_rootpw }}"
  trustAll: ""
  useSsl: ""
  baseDn: '"dc=bkwi,dc=nl"'

#dsc_ustore_createbackend_sroot:
#  hostname: "{{ ds_hostname }}"
#  port: 4444
#  bindDN:  '"cn=Directory Manager"'
#  bindPassword: "{{ ds_rootpw }}"
#  trustAll: ""
#  no-prompt: ""
#  set:
#    - "base-dn:'c=NL'"
#    - enabled:true
#    - db-cache-percent:5
#  type: je
#  backend-name: suwiRoot

#dsc_ustore_createbackend_uroot:
#  hostname: "{{ ds_hostname }}"
#  port: 4444
#  bindDN:  '"cn=Directory Manager"'
#  bindPassword: "{{ ds_rootpw }}"
#  trustAll: ""
#  no-prompt: ""
#  set:
#    - "base-dn:'dc=bkwi,dc=nl'"
#    - enabled:true
#    - db-cache-percent:5
#  type: je 
#  backend-name: userRoot


dsc_ustore_sroot_modify:
  hostname: "{{ ds_hostname }}"
  port: 4444
  bindDN:  '"cn=Directory Manager"'
  bindPassword: "{{ ds_rootpw }}"
  trustAll: ""
  useSsl: ""
  filename: "{{ ds_home }}/{{ ds_home|basename }}-{{ ds_version }}/bkwi/userstore.suwiRoot.ldif"


dsc_ustore_uroot_modify:
  hostname: "{{ ds_hostname }}"
  port: 4444
  bindDN:  '"cn=Directory Manager"'
  bindPassword: "{{ ds_rootpw }}"
  trustAll: ""
  useSsl: ""
  filename: "{{ ds_home }}/{{ ds_home|basename }}-{{ ds_version }}/bkwi/userstore.userRoot.ldif"


dsc_ustore_special_inquire:
  hostname: "{{ ds_hostname }}"
  port: 4444
  bindDN:  '"cn=Directory Manager"'
  bindPassword: "{{ ds_rootpw }}"
  trustAll: ""
  useSsl: ""
  baseDn: '"o=special,c=NL"'


dsc_ustore_suwi_inquire:
  hostname: "{{ ds_hostname }}"
  port: 4444
  bindDN:  '"cn=Directory Manager"'
  bindPassword: "{{ ds_rootpw }}"
  trustAll: ""
  useSsl: ""
  baseDn: '"o=suwi,c=NL"'


dsc_ustore_special_modify:
  hostname: "{{ ds_hostname }}"
  port: 4444
  bindDN:  '"cn=Directory Manager"'
  bindPassword: "{{ ds_rootpw }}"
  trustAll: ""
  useSsl: ""
  filename: "{{ ds_home }}/{{ ds_home|basename }}-{{ ds_version }}/bkwi/organization.special.ldif"

dsc_ustore_suwi_modify:
  hostname: "{{ ds_hostname }}"
  port: 4444
  bindDN:  '"cn=Directory Manager"'
  bindPassword: "{{ ds_rootpw }}"
  trustAll: ""
  useSsl: ""
  filename: "{{ ds_home }}/{{ ds_home|basename }}-{{ ds_version }}/bkwi/organization.suwi.ldif"

dsc_user_reports_inquire:
  hostname: "{{ ds_hostname }}"
  port: 4444
  bindDN:  '"cn=Directory Manager"'
  bindPassword: "{{ ds_rootpw }}"
  trustAll: ""
  useSsl: ""
  baseDn: '"cn=sa_reports,o=special,c=NL"'

dsc_user_reports_modify:
  hostname: "{{ ds_hostname }}"
  port: 4444
  bindDN:  '"cn=Directory Manager"'
  bindPassword: "{{ ds_rootpw }}"
  trustAll: ""
  useSsl: ""
  filename: "{{ ds_home }}/{{ ds_home|basename }}-{{ ds_version }}/bkwi/special.sa_reports.ldif"

dsc_user_reports_pw:
  hostname: "{{ ds_hostname }}"
  port: 4444
  bindDN:  '"cn=Directory Manager"'
  bindPassword: "{{ ds_rootpw }}"
  trustAll: ""
  useSsl: ""
  authzId: "cn=sa_reports,o=special,c=NL"
  newPassword: opends

dsc_user_monitor_inquire:
  hostname: "{{ ds_hostname }}"
  port: 4444
  bindDN:  '"cn=Directory Manager"'
  bindPassword: "{{ ds_rootpw }}"
  trustAll: ""
  useSsl: ""
  baseDn: '"cn=sa_monitor,o=special,c=NL"'

dsc_user_monitor_modify:
  hostname: "{{ ds_hostname }}"
  port: 4444
  bindDN:  '"cn=Directory Manager"'
  bindPassword: "{{ ds_rootpw }}"
  trustAll: ""
  useSsl: ""
  filename: "{{ ds_home }}/{{ ds_home|basename }}-{{ ds_version }}/bkwi/special.sa_monitor.ldif"

dsc_user_monitor_pw:
  hostname: "{{ ds_hostname }}"
  port: 4444
  bindDN:  '"cn=Directory Manager"'
  bindPassword: "{{ ds_rootpw }}"
  trustAll: ""
  useSsl: ""
  authzId: "cn=sa_monitor,o=special,c=NL"
  newPassword: opends

dsc_user_useradmin_inquire:
  hostname: "{{ ds_hostname }}"
  port: 4444
  bindDN:  '"cn=Directory Manager"'
  bindPassword: "{{ ds_rootpw }}"
  trustAll: ""
  useSsl: ""
  baseDn: '"cn=sa_useradmin,o=special,c=NL"'

dsc_user_useradmin_modify:
  hostname: "{{ ds_hostname }}"
  port: 4444
  bindDN:  '"cn=Directory Manager"'
  bindPassword: "{{ ds_rootpw }}"
  trustAll: ""
  useSsl: ""
  filename: "{{ ds_home }}/{{ ds_home|basename }}-{{ ds_version }}/bkwi/special.sa_useradmin.ldif"

dsc_user_useradmin_pw:
  hostname: "{{ ds_hostname }}"
  port: 4444
  bindDN:  '"cn=Directory Manager"'
  bindPassword: "{{ ds_rootpw }}"
  trustAll: ""
  useSsl: ""
  authzId: "cn=sa_useradmin,o=special,c=NL"
  newPassword: opends

dsc_amconfigpw_inquire:
  hostname: "{{ ds_hostname }}"
  port: 4444
  bindDN:  '"cn=Directory Manager"'
  bindPassword: "{{ ds_rootpw }}"
  trustAll: ""
  useSsl: ""
  baseDn: '"uid=am-config,ou=admins,ou=am-config"'

dsc_amconfigpw_modify:
  hostname: "{{ ds_hostname }}"
  port: 4444
  bindDN:  '"cn=Directory Manager"'
  bindPassword: "{{ ds_rootpw }}"
  trustAll: ""
  useSsl: ""
  filename: "{{ ds_home }}/{{ ds_home|basename }}-{{ ds_version }}/bkwi/passwordpolicy.am-config.ldif"

# Password policy settings
ds_config_pps:
  generic:
    - default-password-storage-scheme:Salted SHA-512
    - password-attribute:userPassword
    - deprecated-password-storage-scheme:Salted SHA-1
    - last-login-time-attribute:ds-pwp-last-login-time
    - last-login-time-format:yyyyMMddHHmmss
    - password-expiration-warning-interval:7 days
    - min-password-age:24 hours
    - password-change-requires-current-password:true
    - password-history-duration:0 seconds
    - skip-validation-for-administrators:true
    - require-secure-authentication:true
  default:
    - allow-user-password-changes:true
    - expire-passwords-without-warning:true
    - force-change-on-add:true
    - force-change-on-reset:true
    - grace-login-count:2
    - idle-lockout-interval:45 days
    - lockout-duration:0 minutes
    - lockout-failure-expiration-interval:0 minutes
    - lockout-failure-count:5
    - max-password-age:56 days
    - max-password-reset-age:14 days
    - password-history-count:10
    - require-secure-password-changes:true
  service-accounts:
    - expire-passwords-without-warning:false
    - force-change-on-add:false
    - force-change-on-reset:false
    - grace-login-count:10
    - idle-lockout-interval:2000 days
    - lockout-duration:1 s
    - lockout-failure-expiration-interval:1 s
    - lockout-failure-count:10000
    - max-password-age:2000 days
    - max-password-reset-age:8 hours
    - password-history-count:5
    - require-secure-password-changes:true
  jmx:
    - default-password-storage-scheme:Salted SHA-512
    - expire-passwords-without-warning:false
    - force-change-on-add:false
    - force-change-on-reset:false
    - grace-login-count:10
    - idle-lockout-interval:2000 days
    - lockout-duration:480 s
    - lockout-failure-expiration-interval:600 s
    - lockout-failure-count:5
    - max-password-age:2000 days
    - max-password-reset-age:8 hours
    - password-history-count:5
    - password-history-duration:0 seconds

ds_config:
  connection-handler_set_cert: # note underscore → connection-handler component
    - handler-name: LDAPS
      add: ssl-cert-nickname:config-server-cert
  connection-handler:
    - handler-name: LDAP
      set: enabled:false
    - handler-name: LDAPS
      set: allow-ldap-v2:true
  global-configuration:
    - set: lookthrough-limit:20000
    - set: smtp-server:127.0.0.1:25
  log-publisher:
    - publisher-name: File-Based Access Logger
      set: enabled:false
  password-policy_create:
    - policy-name: Default Password Policy
      type: password-policy
      set:
        - default-password-storage-scheme:Salted SHA-512
        - password-attribute:userPassword
      when:
        regex: '^(Default Password Policy)\s+:'
        method: list-password-policies
        match: no
        #switches:
        #  property: password-attribute
  password-policy:
    - policy-name: Default Password Policy
      set: "{{ ds_config_pps['generic'] + ds_config_pps['default'] }}"
      add:
        - password-validator:Length-Based Password Validator
        - password-validator:Similarity-Based Password Validator
        - password-validator:Attribute Value
        - password-validator:Unique Characters
        - password-validator:Character Set
  password-policy_remove:
    - policy-name: Default Password Policy
      remove: password-validator:At least 8 characters
      when:
        regex: '^password-validator\s:[\S\s.]*(\sAt least 8 characters)[\s,].*$'
        method: get-password-policy-prop
        match: yes
        switches:
           policy-name: Default Password Policy
           property: password-validator
    - policy-name: Default Password Policy
      remove: password-validator:Common passwords
      when:
        regex: '^password-validator\s:[\S\s.]*(\sCommon passwords)[\s,].*$'
        method: get-password-policy-prop
        match: yes
        switches:
           policy-name: Default Password Policy
           property: password-validator
    - policy-name: Default Password Policy
      remove: password-validator:Dictionary
      when:
        regex: '^password-validator\s:[\S\s.]*(\sDictionary)[\s,].*$'
        method: get-password-policy-prop
        match: yes
        switches:
           policy-name: Default Password Policy
           property: password-validator
    - policy-name: Default Password Policy
      remove: password-validator:Repeated Characters
      when:
        regex: '^password-validator\s:[\S\s.]*(\sRepeated Characters)[\s,].*$'
        method: get-password-policy-prop
        match: yes
        switches:
           policy-name: Default Password Policy
           property: password-validator
  password-policy_service-accounts-create:
    - policy-name: Password Policy Service Accounts
      type: password-policy
      set:
        - default-password-storage-scheme:Salted SHA-512
        - password-attribute:userPassword
  password-policy_service-accounts:
    - policy-name: Password Policy Service Accounts
      set: "{{ ds_config_pps['generic'] + ds_config_pps['service-accounts'] }}"
  password-policy_service-accounts-jmx-create:
    - policy-name: Password Policy JMX Service Accounts
      type: password-policy
      set:
        - default-password-storage-scheme:Salted SHA-512
        - password-attribute:userPassword
  password-policy_service-accounts-jmx:
    - policy-name: Password Policy JMX Service Accounts
      set: "{{ ds_config_pps['generic'] + ds_config_pps['jmx'] }}"
  password-validator:
    - validator-name: '"Length-Based Password Validator"'
      set:
        - enabled:true
        - min-password-length:8
        - max-password-length:0
    - validator-name: '"Similarity-Based Password Validator"'
      set:
        - enabled:true
        - min-password-difference:3
    - validator-name: '"Attribute Value"'
      set: enabled:true
      add:
        - match-attribute:cn
        - match-attribute:sn
        - match-attribute:givenName
        - match-attribute:uid
    - validator-name: '"Unique Characters"'
      set:
        - enabled:true
        - min-unique-characters:4
        - case-sensitive-validation:true
    - validator-name: '"Character Set"'
      set:
        - enabled:true
        - allow-unclassified-characters:true
  backend_create:
    - set:
        - base-dn:c=NL
        - enabled:true
        - db-cache-percent:5
      type: je
      backend-name: suwiRoot
    - set:
        - base-dn:dc=bkwi,dc=nl
        - enabled:true
        - db-cache-percent:5
      type: je
      backend-name: userRoot
#  password-validator_add:
#    - validator-name: '"Attribute Value"'
#      set: enabled:true
#      add:
#        - match-attribute:cn
#        - match-attribute:sn
#        - match-attribute:givenName
#        - match-attribute:uid
#      #remove:
#      #  - match-attribute:sn

ds_config_components:
  - connection-handler
  - global-configuration
  - log-publisher
  - password-policy_create
  - password-policy
  - password-policy_service-accounts-create
  - password-policy_service-accounts
  - password-policy_service-accounts-jmx-create
  - password-policy_service-accounts-jmx
  - password-validator
  - password-policy_remove
  - backend_create
  #- password-validator_add

# Components that require use of a fingerpint to detect
# changes between current and desired state
ds_config_components_fingerprint:
  - connection-handler
  #- password-validator_add
  #- password-policy_create
  - password-policy
  - password-policy_service-accounts-create
  - password-policy_service-accounts
  - password-policy_service-accounts-jmx-create
  - password-policy_service-accounts-jmx
  - backend_create
