---
namespace: c2platform
name: forgerock
version: "0.1.5"
readme: README.md
authors:
  - Onno van der Straaten (onno@onknows.com)
license_file: LICENSE

description: C2 Platform Ansible Collection for ForgeRock IG, DS and AM

tags:
  - c2platform
  - forgerock
  - am
  - ig
  - ds

dependencies: {}

repository: https://github.com/c2platform/ansible-collection-forgerock
documentation: https://github.com/c2platform/ansible-collection-forgerock
homepage: https://github.com/c2platform/
issues: https://github.com/c2platform/ansible-collection-forgerock/issues

build_ignore: []
