---
- name: Create owner
  user:
    name: "{{ ig_owner }}"
    shell: /bin/bash
    system: true

- name: Create home
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ig_owner }}"
    group: "{{ ig_group }}"
    mode: 0755
  with_items:
    - "{{ ig_home }}"
    - "{{ ig_home_version }}"
    - "{{ ig_home_version }}/.openig"
    - "{{ ig_home_version }}/.openig/config"
    - "{{ ig_home_version }}/.openig/config/routes"
    - "{{ ig_home_version }}/.openig/scripts"
    - "{{ ig_home_version }}/.openig/scripts/groovy"

# As for chmod rights, Chef/XLS has a mixture of 700-becoming-755, 500 and 644. We'll try with this
# highest/unsafest level first, if any tool requires a lower/safer level we'll adjust.

- name: Get templated configs in place
  template:
    src: "{{ item }}.json.j2"
    dest:  "{{ ig_home_version }}/.openig/config/{{ item }}.json"
    owner: "{{ ig_owner  }}"
    group: "{{ ig_group }}"
    mode: 0755
  with_items:
    - config
    - properties

- name: Get templated routes in place
  template:
    src: "{{ item }}.json.j2"
    dest:  "{{ ig_home_version }}/.openig/config/routes/{{ item }}.json"
    owner: "{{ ig_owner  }}"
    group: "{{ ig_group }}"
    mode: 0755
  with_items:
    - 111-not_enforced
    - 112-local_static_content
    - 121-ipwhitelisting-template
    - 202-suwinet-inkijk-pep
    - 900_not_found

- name: Rewrite paths
  template:
    src: RewritePath.groovy.j2
    dest: "{{ ig_home_version }}/.openig/scripts/groovy/{{ item['name'] }}.groovy"
    owner: "{{ ig_owner }}"
    group: "{{ ig_group }}"
    mode: 0644
  with_items: "{{ ig_rewrite_paths }}"
  when: ig_rewrite_paths is defined
