---
- name: Create owner
  user:
    name: "{{ ig_owner }}"
    shell: /bin/bash
    system: true

- name: Create home
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ig_owner }}"
    group: "{{ ig_group }}"
    mode: 0755
  with_items:
    - "{{ ig_home }}"
    - "{{ ig_home }}/{{ ig_version }}"

- include: install.yml
