---
- name: DS config set certificate
  include_tasks: config_component.yml
  vars:
    component: connection-handler_set_cert
    skip_state_check: yes
  when: ds_setup # first / setup run

- include_tasks: config_component.yml
  with_items: "{{ ds_config_components }}"
  vars:
    use_fingerprint: "{{ component in ds_config_components_fingerprint }}"
  loop_control:
    loop_var: component
