---
- block:
    - name: "Fingerprint {{ component }}"
      copy:
        content: "{{ ds_config[component]|c2platform.forgerock.ds_config_fingerprint }}"
        dest: "{{ component|c2platform.forgerock.ds_config_fingerprint_component_path(ds_home,ds_version) }}"
        group: "{{ ds_owner }}"
        owner: "{{ ds_group }}"
        mode: 0664
      when: use_fingerprint
      register: component_fingerprint

    - name: "Get current configuration {{ component }}"
      shell: >
        ./dsconfig {{ component|c2platform.forgerock.ds_config_method(item,'get') }}
        {{ ds_connect|c2platform.forgerock.ds_cmd }}
        {{ item|c2platform.forgerock.ds_cmd_get(component) }}
      environment: "{{ ds_environment }}"
      with_items: "{{ ds_config[component] }}"
      args:
        chdir: "{{ ds_home_version }}/bin"
      register: current_config
      when: not use_fingerprint
      changed_when: False
  when: not skip_state_check|default(False)

- name: "Set component {{ component }}"  # noqa ignore-errors
  shell: >
    ./dsconfig {{ component|c2platform.forgerock.ds_config_method }}
    {{ ds_connect|c2platform.forgerock.ds_cmd }}
    {{ item|c2platform.forgerock.ds_cmd }}
  environment: "{{ ds_environment }}"
  with_items: "{{ ds_config[component] }}"
  when:
    - item|c2platform.forgerock.ds_config_state_diff(current_config,component_fingerprint,use_fingerprint,skip_state_check|default(False))
  args:
    chdir: "{{ ds_home_version }}/bin"
  ignore_errors: "{{ ds_config_ignore_errors|default(False) }}"
