---
- name: "Prepare config {{ component }}"
  c2platform.forgerock.ds_config_component:
    component: "{{ component }}"
    config: "{{ ds_config[component] }}"
    get: "{{ ds_component_get }}"
  register: _dscc

- name: Get current config
  shell: >
    ./dsconfig {{ item['get-cmd'] }}
    {{ ds_connect|c2platform.forgerock.ds_cmd }}
  environment: "{{ ds_environment }}"
  with_items: "{{ _dscc['config']|selectattr('get-cmd', 'defined')|list }}"
  loop_control:
    label: "{{ component }}-{{ item['step'] }} {{ item['method'] }}"
  args:
    chdir: "{{ ds_home_version }}/bin"
  register: ds_config_current
  changed_when: False

- name: Prepare config ( add current )
  c2platform.forgerock.ds_config_component:
    component: "{{ component }}"
    config: "{{ ds_config[component] }}"
    get: "{{ ds_component_get }}"
    config_current: "{{ ds_config_current.results|list }}"
  register: ds_config_prepared

- name: Change config
  shell: >
    {{ ds_home_version }}/bin/dsconfig {{ item['cmd'] }}
    {{ ds_connect|c2platform.forgerock.ds_cmd }}
  environment: "{{ ds_environment }}"
  with_items: "{{ ds_config_prepared['config']|list }}"
  loop_control:
    label: "{{ component }}-{{ item['step'] }} {{ item['method'] }}"
  when: ds_component_when[item['method']]['when']
  changed_when: ds_component_when[item['method']]['changed_when']|default(omit)
  register: ds_config_changes

- name: "Prepare config ( add results )"
  c2platform.forgerock.ds_config_component:
    component: "{{ component }}"
    config: "{{ ds_config[component] }}"
    get: "{{ ds_component_get }}"
    config_current: "{{ ds_config_current.results|list }}"
    config_changes: "{{ ds_config_changes.results|list }}"
  register: ds_config_changes

- name: Log config
  copy: # debug
    content: "{{ ds_config_changes['config']|to_nice_yaml }}"
    dest: "{{ ds_home_version }}/logs/dsconfig-{{ component }}.yml"
