---


- name: Create userstore ldifs
  copy:
    content: "{{ ds_userstore_ldifs[item] }}"
    remote_src: yes
    dest: "{{ ds_home_version }}/bkwi/./{{ item }}.ldif"
    owner: "{{ ds_owner }}"
    group: "{{ ds_group }}"
    mode: '0640'
  with_items: "{{ ds_userstore_ldifs }}"



- name: Userstore suwiRoot exists already ?
# The actual check on the result is in the 'when' clause for the dsconfig and ldapmodify, see below.
# Last parameter is dashless hence hardcoded here.
  shell:  "./ldapsearch  {{ dsc_ustore_sroot_inquire|c2platform.forgerock.ds_cmd }} objectclass=top"
  become: yes
  become_user: forgerock
  args:
    chdir: "{{ ds_home_version }}/bin"
  register: ustore_sroot_inquire
  ignore_errors: yes
# Small warning - the Chef logic leads to a check with --baseDn c=NL. That is not unique,  it also yields
# the organization.suwi and .special schemas as these have a baseDN with c=NL as _sub_string
# Not clear yet whether this is  a real bug or just an irrelevant detail.


  
- name: Modify DS with suwiRoot
  shell:  "./ldapmodify  {{ dsc_ustore_sroot_modify|c2platform.forgerock.ds_cmd }}"
  become: yes
  become_user: forgerock
  args:
    chdir: "{{ ds_home_version }}/bin"
  when: ustore_sroot_inquire is search("No Such Entry")

- name: Userstore userRoot exists already ?
# The actual check on the result is in the 'when' clause for the dsconfig etc, see below.
# Last parameter is dashless hence hardcoded here
  shell:  "./ldapsearch  {{ dsc_ustore_uroot_inquire|c2platform.forgerock.ds_cmd }} objectclass=top"
  become: yes
  become_user: forgerock
  args:
    chdir: "{{ ds_home_version }}/bin"
  register: ustore_uroot_inquire
  ignore_errors: yes

- name: Modify DS with userRoot
  shell:  "./ldapmodify  {{ dsc_ustore_uroot_modify|c2platform.forgerock.ds_cmd }}"
  become: yes
  become_user: forgerock
  args:
    chdir: "{{ ds_home_version }}/bin"
  when: ustore_uroot_inquire is search("No Such Entry")


- name: Userstore special exists already ?
# The actual check on the result is in the 'when' clause for the dsconfig etc, see below.
# Last parameter is dashless hence hardcoded here
  shell:  "./ldapsearch  {{ dsc_ustore_special_inquire|c2platform.forgerock.ds_cmd }} objectclass=organization"
  become: yes
  become_user: forgerock
  args:
    chdir: "{{ ds_home_version }}/bin"
  register: ustore_special_inquire
  ignore_errors: yes

- name: modify DS with special
  shell:  "./ldapmodify  {{ dsc_ustore_special_modify|c2platform.forgerock.ds_cmd }}"
  become: yes
  become_user: forgerock
  args:
    chdir: "{{ ds_home_version }}/bin"
  when: ustore_special_inquire is search("No Such Entry")

- name: Userstore suwi exists already ?
# The actual check on the result is in the 'when' clause for the dsconfig etc, see below.
# Last parameter is dashless hence hardcoded here
  shell:  "./ldapsearch  {{ dsc_ustore_suwi_inquire|c2platform.forgerock.ds_cmd }} objectclass=organization"
  become: yes
  become_user: forgerock
  args:
    chdir: "{{ ds_home_version }}/bin"
  register: ustore_suwi_inquire
  ignore_errors: yes

- name: Modify DS with suwi
  shell:   "./ldapmodify  {{ dsc_ustore_suwi_modify|c2platform.forgerock.ds_cmd }}"
  become: yes
  become_user: forgerock
  args:
    chdir: "{{ ds_home_version }}/bin"
  when: ustore_suwi_inquire is search("No Such Entry")