---


- name: DSconfig set certificate
  command: "./dsconfig set-connection-handler-prop {{ dsconf_cert|c2platform.forgerock.ds_cmd }}"
  # Skeleton values for the setup are in defaults of DS role, and actual values in group_vars or the Ansible play
  # Note that for dsconfig parameters, IGNORE the Forgerock website docu and use the dsconfig --help info instead!
  # The when: condition reuses the status --offline check outcome in install.yml
  become: yes
  become_user: forgerock
  args:
    chdir: "{{ ds_home }}/{{ ds_home|basename }}-{{ ds_version }}/bin" 
  when:  ds_status is search("The server has not been configured") 
  register: cert_status


- name: Create BKWI subdir
  file:
    path: "{{ ds_home }}/{{ ds_home|basename }}-{{ ds_version }}/bkwi" 
    state: directory
    owner: "{{ ds_owner }}"
    group: "{{ ds_group }}"
    mode: 0755

# Section Set component settings

- name:  DSC-config set lookthrough  
  command: "./dsconfig set-global-configuration-prop {{ dsc_conf_look|c2platform.forgerock.ds_cmd }}"
  become: yes
  become_user: forgerock
  args:
    chdir: "{{ ds_home }}/{{ ds_home|basename }}-{{ ds_version }}/bin" 

- name:  DSC-config set smtp 
  command: "./dsconfig set-global-configuration-prop {{ dsc_conf_smtp|c2platform.forgerock.ds_cmd }}"
  become: yes
  become_user: forgerock
  args:
    chdir: "{{ ds_home }}/{{ ds_home|basename }}-{{ ds_version }}/bin" 
  
# Section Set connection handler settings

- name: DSC-connectionhandler set LDAP
  command: "./dsconfig set-connection-handler-prop {{ dsc_connect_LDAP|c2platform.forgerock.ds_cmd }}"
  become: yes
  become_user: forgerock
  args:
    chdir: "{{ ds_home }}/{{ ds_home|basename }}-{{ ds_version }}/bin"

- name: DSC-connectionhandler set LDAPS
  command: "./dsconfig set-connection-handler-prop {{ dsc_connect_LDAPS|c2platform.forgerock.ds_cmd }}"
  become: yes
  become_user: forgerock
  args:
    chdir: "{{ ds_home }}/{{ ds_home|basename }}-{{ ds_version }}/bin"

# Section Set log publisher settings

- name: DSC-logpublisher filebased
  command: "./dsconfig set-log-publisher-prop {{ dsc_logger_file|c2platform.forgerock.ds_cmd }}"
  become: yes
  become_user: forgerock
  args:
    chdir: "{{ ds_home }}/{{ ds_home|basename }}-{{ ds_version }}/bin"


- name: DSC-logpublisher  debug
  debug:
    msg: "./dsconfig set-log-publisher-prop {{ dsc_logger_test|c2platform.forgerock.ds_cmd }}"


- name: Copy suwinetPerson ldif file
# Note that source location is really for DEV only, it was copied from 
# https://gitlab.bkwi.nl/bkwi-dxc/sbp-data/-/blob/master/gitlab_projects/BKWI-Suwi-Cookbooks/bkw_ds_role/files/default/suwinetPerson.ldif
# But for Ansible BTO another BKWI git location is the plan. And then we'll make the source path below using a variable too.
  copy:
    src:  /vagrant/downloads/suwinetPerson.ldif
    remote_src: yes
    dest: "{{ ds_home }}/{{ ds_home|basename }}-{{ ds_version }}/db/schema/./suwinetPerson.ldif"
    owner: "{{ ds_owner }}"
    group: "{{ ds_group }}"
    mode: '0640'




- name: Password policy  - exists Default ?
# The actual check on the result is in the 'when' clauses  for the 2 setups, see below
  shell:  "./dsconfig get-password-policy-prop {{ dsc_pol_default_inquire|c2platform.forgerock.ds_cmd }}"
  become: yes
  become_user: forgerock
  args:
    chdir: "{{ ds_home }}/{{ ds_home|basename }}-{{ ds_version }}/bin"
  register: pol_default_inquire
  ignore_errors: yes

- name: debug cert_status 
  debug:
    msg: "{{ pol_default_inquire }}"
