---
- name: DS config set certificate
  include_tasks: config_component.yml
  vars:
    component: connection-handler_set_cert
    skip_state_check: yes
  when: ds_setup # first / setup run

- name: Create BKWI subdir
  file:
    path: "{{ ds_home_version }}/bkwi"
    state: directory
    owner: "{{ ds_owner }}"
    group: "{{ ds_group }}"
    mode: 0755

- include_tasks: config_component.yml
  with_items: "{{ ds_config_components }}"
  vars:
    use_fingerprint: "{{ component in ds_config_components_fingerprint }}"
  loop_control:
    loop_var: component

- name: Create db schema ldifs
  copy:
    content: "{{ ds_db_schema_ldifs[item] }}"
    remote_src: yes
    dest: "{{ ds_home_version }}/db/schema/./{{ item }}.ldif"
    owner: "{{ ds_owner }}"
    group: "{{ ds_group }}"
    mode: '0640'
  with_items: "{{ ds_db_schema_ldifs }}"
  when: ds_db_schema_ldifs|default(False)
