---
- name: "Prepare config {{ component }}"
  c2platform.forgerock.ds_config_component:
    component: "{{ component }}"
    config: "{{ ds_config[component] }}"
    get_methods: "{{ ds_config_get_methods }}"
  register: ds_config_prepared

- name: ds_config prepared
  set_fact:
    ds_config: "{{ ds_config|combine(ds_config_prepared['config']) }}"

- include: config_log.yml
  when: ds_debug

- name: Get current config
  shell: >
    ./dsconfig {{ item['get']['cmd'] }}
    {{ ds_connect|c2platform.forgerock.ds_cmd }}
  environment: "{{ ds_environment }}"
  with_items: "{{ ds_config[component]|list }}"
  loop_control:
    label: "{{ component_index }}-{{ component }}-{{ item['step'] }} {{ item['get']['method'] }} {{ item['comment']|default('') }}"
  args:
    chdir: "{{ ds_home_version }}/bin"
  register: ds_config_current
  when: item['enabled']|default(True)
  changed_when: False

- name: Prepare config ( add current )
  c2platform.forgerock.ds_config_component:
    component: "{{ component }}"
    config: "{{ ds_config[component] }}"
    get_methods: "{{ ds_config_get_methods }}"
    config_current: "{{ ds_config_current.results|list }}"
  register: ds_config_prepared_2

- name: ds_config current
  set_fact:
    ds_config: "{{ ds_config|combine(ds_config_prepared_2['config']) }}"

- include: config_log.yml
  when: ds_debug

- name: Change config
  shell: >
    {{ ds_home_version }}/bin/dsconfig {{ item['cmd'] }}
    {{ ds_connect|c2platform.forgerock.ds_cmd }}
  environment: "{{ ds_environment }}"
  with_items: "{{ ds_config[component]|list }}"
  loop_control:
    label: "{{ component_index }}-{{ component }}-{{ item['step'] }} {{ item['method'] }}"
  when: item['change']
  changed_when: item['changed_when']|default(omit)
  register: ds_config_changes

- name: "Prepare config ( add results )"
  c2platform.forgerock.ds_config_component:
    component: "{{ component }}"
    config: "{{ ds_config[component] }}"
    get_methods: "{{ ds_config_get_methods }}"
    config_current: "{{ ds_config_current.results|list }}"
    config_changes: "{{ ds_config_changes.results|list }}"
  register: ds_config_changes

- name: ds_config changes
  set_fact:
    ds_config: "{{ ds_config|combine(ds_config_changes['config']) }}"

- include: config_log.yml
  when: ds_debug
