---
- include_tasks: config_component.yml
  with_indexed_items: "{{ ds_config_components }}"
  vars:
    component: "{{ indexed_component.1 }}"
    component_index: "{{ indexed_component.0 }}"
  loop_control:
    loop_var: indexed_component
  when: ds_config_components is defined and ds_config_enabled|default(True)

- include: config_log.yml  # log ds_config
