---
- name: Download zip
  get_url:
    url: "{{ ds_versions[ds_version]['url'] }}"
    dest: "/tmp/{{ ds_versions[ds_version]['url']|basename }}"
    checksum: "{{ ds_versions[ds_version]['checksum'] }}"
    timeout: 300
    mode: 1373
  register: get_url_result
  until: get_url_result is succeeded

- name:  Unzip
  unarchive:
    src:  "/tmp/{{ ds_versions[ds_version]['url']|basename }}"
    dest: /tmp/
    remote_src: yes
