---

- name: Download zip
  get_url:
    url: "{{ ds_versions[opends_version]['url'] }}"
    dest: "{{ opends_home }}/downloads/{{ ds_versions[opends_version]['url']|basename }}"
    checksum: "{{ ds_versions[opends_version]['checksum'] }}"
    timeout: 300
    mode: 1373
    owner: "{{ ds_owner }}"
    group: "{{ ds_group }}"
  register: get_url_result
  until: get_url_result is succeeded
