---


- name: Exit if the  host is not config_master (but the config slave)
  fail: msg="Provisioning finished, replication is configured from the other node"
  when: not dsrepl_is_config_master

- name:  Create replication settings
  shell:  "./dsreplication configure {{ dsr_config|c2platform.forgerock.ds_cmd }}"
  become: yes
  become_user: forgerock
  args:
    chdir: "{{ ds_home }}/{{ ds_home|basename }}-{{ ds_version }}/bin"
  with_items: "{{ dsr_baseDNlist }}"
  ignore_errors: yes #to be removed


- name:  Initialize replication
  shell:  "./dsreplication initialize-all {{ dsr_init|c2platform.forgerock.ds_cmd }}"
  become: yes
  become_user: forgerock
  args:
    chdir: "{{ ds_home }}/{{ ds_home|basename }}-{{ ds_version }}/bin"
  with_items: "{{ dsr_baseDNlist }}"
  ignore_errors: yes #to be removed