---
- name: Ensure group forgerock exists
  group:
    name: "{{ ds_group }}"
    state: present

- name: Create owner
  user:
    name: "{{ ds_owner }}"
    group: "{{ ds_group }}"
    home: "{{ ds_home }}"
    shell: /bin/bash
    system: true

- name: Create home
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ds_owner }}"
    group: "{{ ds_group }}"
    mode: 0755
  with_items:
    - "{{ ds_home }}"
    - "{{ ds_home }}/downloads"
    - "{{ ds_home }}/{{ ds_home|basename }}-{{ ds_version }}"
#    - "{{ ds_home }}/{{ ds_home|basename }}-{{ ds_version }}/config"

- name: Add specific limits for ds_owner in limits.conf
  community.general.pam_limits:
    domain: forgerock
    limit_type: soft
    limit_item: nofile
    value: 65536

- name: Add 2nd limit
  community.general.pam_limits:
    domain: forgerock
    limit_type: hard
    limit_item: nofile
    value: 131072

- name: Download zip
  get_url:
    url: "{{ ds_versions[ds_version]['url'] }}"
    dest: "{{ ds_home }}/downloads/{{ ds_versions[ds_version]['url']|basename }}"
    checksum: "{{ ds_versions[ds_version]['checksum'] }}"
    timeout: 300
    mode: 1373
    owner: "{{ ds_owner }}"
    group: "{{ ds_group }}"
  register: get_url_result
  until: get_url_result is succeeded
