---
- name: Stat home folder # e.g. /opt/ds/ds-6.5.4
  stat:
    path: "{{ ds_home }}/{{ ds_home|basename }}-{{ ds_version }}"
  register: home_folder

- block:
    - name: Download zip
      get_url:
        url: "{{ ds_versions[ds_version]['url'] }}"
        dest: "/tmp/{{ ds_versions[ds_version]['url']|basename }}"
        checksum: "{{ ds_versions[ds_version]['checksum'] }}"
        timeout: 300
        mode: 1373
      register: get_url_result
      until: get_url_result is succeeded

    - name:  Unzip
      unarchive:
        src:  "/tmp/{{ ds_versions[ds_version]['url']|basename }}"
        dest: /tmp/
        remote_src: yes

    - name: Create group
      group:
        name: "{{ ds_group }}"
        state: present

    - name: Create owner
      user:
        name: "{{ ds_owner }}"
        group: "{{ ds_group }}"
        home: "{{ ds_home }}"
        shell: /bin/bash
        system: true

    - name: Create home
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ ds_owner }}"
        group: "{{ ds_group }}"
        mode: 0755
        recurse: yes
      with_items:
        - "{{ ds_home }}"
        - "{{ ds_home }}/{{ ds_home|basename }}-{{ ds_version }}"
        - "{{ ds_home|c2platform.forgerock.ds_config_fingerprint_folder(ds_version) }}"

    - name: Make sure zip is on target
      synchronize:
        src: /tmp/opendj/
        dest: "{{ ds_home }}/{{ ds_home|basename }}-{{ ds_version }}/"
      delegate_to: "{{ inventory_hostname }}"

    - name: Chown
      file:
        path: "{{ ds_home }}"
        owner: "{{ ds_owner }}"
        group: "{{ ds_group }}"
        recurse: yes
  when: not home_folder.stat.exists
