---

- name:  Unzip  DS
  unarchive:
    src:  "{{ ds_home }}/downloads/{{ ds_versions[ds_version]['url']|basename }}"
    dest: "{{ ds_home }}/{{ ds_home|basename }}-{{ ds_version }}"
    owner: "{{ ds_owner }}"
    group: "{{ ds_group }}"
    remote_src: yes

- name: remove opendj layer coming from unpacked zip
  shell: "mv {{ ds_home }}/{{ ds_home|basename }}-{{ ds_version }}/opendj/* {{ ds_home }}/{{ ds_home|basename }}-{{ ds_version }}"
  become: yes
  become_user: forgerock
  ignore_errors: yes

- name: erase opendj dir even if filled due to failed mv (double run)
  file:
    path:  "{{ ds_home }}/{{ ds_home|basename }}-{{ ds_version }}/opendj"
    state: absent

- name: Check whether DS setup already run # noqa 305
# The actual check on the result is in the 'when' clause for the setup, see below
  shell: "{{ ds_home }}/{{ ds_home|basename }}-{{ ds_version }}/bin/status --offline"
  become: yes
  become_user: forgerock
  register: ds_status
  ignore_errors: yes

- name: debug cert_status
  debug:
    msg: "{{ ds_setup_config }}"

- name: Setup ds config
  command: "./setup directory-server {{ ds_setup_config|c2platform.forgerock.ds_cmd }}"
  become: yes
  become_user: forgerock
  args:
    chdir: "{{ ds_home }}/{{ ds_home|basename }}-{{ ds_version }}"
  when:  ds_status is search("The server has not been configured")
  register: ds_setup_status

- name: chown recursive (hardly needed)
  file:
    dest: "{{ ds_home }}/{{ ds_home|basename }}-{{ ds_version }}"
    owner: "{{ ds_owner }}"
    group: "{{ ds_group }}"
    recurse: yes

- name: Systemd DS config 2-step level
  template:
    src: dsconfig-init.j2
    dest:  "{{ ds_home }}/{{ ds_home|basename }}-{{ ds_version }}/bin/dsconfig-init.sh"
    owner: root 
    group: root
    mode: 0755


# For explanation of the rather crazy model needed, see https://backstage.forgerock.com/knowledge/kb/article/a56766667
# We do it bottoms-up. First the init script, then the service that calls the init script, and finally the enabling
# Note
that  we deviate from Chef, but result (from our MVP) is same

- name: Systemd DS config service
  template:
    src: dsconfig.service.j2
    dest: /etc/systemd/system/ds-config.service
    owner: root
    group: root
    mode: 0755
  notify: systemctl-daemon-reload

- name: ensure config service (running and) set to start on boot
  service:
    name: ds-config
    enabled: yes


# As during install through the setup command the service gets started, we cannot require 'started' here. Error would be "unable to start service ds-config" :-( 
# The whole two-step install
# mainly accomplishes that start-ds shell script is run upon boot. The perils of running an init.d era startup script in the syemctl Unix era.




