---
- include: install.yml
- include: setup.yml
- include: service.yml
- include: config.yml

- include_tasks: modify.yml
  when: ds_modify|default(False)
  with_items: "{{ ds_modify + (ds_modify_extra|default([])) }}"

- include_tasks: modify_pw.yml
  when: ds_passwords|default(False)

- include: setup_replication.yml
  when: ds_replication['replication-server']['hostname']|default('whatever') == ds_hostname

# Note the README.md and wiki: due to the specific scenario building up a 2-node cluster,
# this replicate part will  be skipped if the node is not configured as the config master
# And it's strongly recommended to provision the not_config_master node BEFORE provisioning the config_master node.
# (There is a sanity check on board to handle human errors here.)
