---
- include: install.yml
- include: setup.yml
- include: service.yml
- include: config.yml

- include_tasks: modify.yml
  when: ds_modify|default(False)
  with_items: "{{ ds_modify + (ds_modify_extra|default([])) }}"

- include_tasks: modify_pw.yml
  when: ds_passwords|default(False)

- include_tasks: import.yml
  when: ds_import|default(False)
  with_items: "{{ ds_import }}"

- include: setup_replication.yml
  when: ds_replication['replication-server']['hostname']|default('whatever') == ds_hostname and ds_replication_enable
