---
- name: "Passwords fingerprint"
  copy:
    content: "{{ ds_passwords|c2platform.forgerock.ds_config_fingerprint }}"
    dest: "{{ 'ds_passwords'|c2platform.forgerock.ds_config_fingerprint_component_path(ds_home,ds_version) }}"
    group: "{{ ds_owner }}"
    owner: "{{ ds_group }}"
  register: passwords_fingerprint

- name: "Modify password"
  shell:  "./ldappasswordmodify  {{ ds_connect_ssl|combine(ds_passwords[item])|c2platform.forgerock.ds_cmd }}"
  environment:
    OPENDJ_JAVA_HOME: "{{ ds_java_home }}"
    JAVA_HOME: "{{ ds_java_home }}"
  args:
    chdir: "{{ ds_home_version }}/bin"
  with_items: "{{ ds_passwords }}"
  when: passwords_fingerprint.changed
