---
- name: "Check {{ item|c2platform.forgerock.dn_from_modify_item }}"
  shell:  "./ldapsearch {{ ds_connect_ssl|c2platform.forgerock.ds_cmd }} {{ item|c2platform.forgerock.ds_modify_search }}"
  args:
    chdir: "{{ ds_home_version }}/bin"
  register: ldapsearch_result
  changed_when: false

- block:
    - name: "Download {{ item['ldif-url'] }}"
      get_url:
        url: "{{ item['ldif-url'] }}"
        dest: "{{ ds_home_version }}/import-tmp/{{ item['name'] }}.ldif"
      when: item['ldif-url'] is defined

    - name: "{{ item['name'] }}.ldif"
      copy:
        content: "{{ item['ldif'] }}"
        remote_src: yes
        dest: "{{ ds_home_version }}/import-tmp/{{ item['name'] }}.ldif"
        owner: "{{ ds_owner }}"
        group: "{{ ds_group }}"
        mode: '0640'
      when: item['ldif'] is defined

    - name: "item {{ item|c2platform.forgerock.dn_from_modify_item }}"
      shell:  "./ldapmodify {{ ds_connect_ssl|c2platform.forgerock.ds_cmd }} --filename {{ ds_home_version }}/import-tmp/{{ item['name'] }}.ldif"
      args:
        chdir: "{{ ds_home_version }}/bin"
  when: ldapsearch_result is search("No Such Entry") or ldapsearch_result.stdout == ""
