---
- name: "Execute script {{ ds_script }}"
  shell: "{{ ds_scripts[ds_script]['shell'] }}"
  args:
    chdir: "{{ ds_scripts[ds_script]['chdir']|default(omit) }}"
  register: ds_script_execute
  changed_when: ds_script_execute['stdout'] is search("Script changed system state")
  ignore_errors: yes
