---
- name: "Execute script {{ ds_script }}"  # noqa command-instead-of-shell
  shell: "{{ ds_scripts[ds_script]['shell'] }}"
  args:
    chdir: "{{ ds_scripts[ds_script]['chdir']|default(omit) }}"
  register: ds_script_execute
  changed_when: ds_script_execute['stdout'] is search("Script changed system state")
  ignore_errors: yes

- name: Debug ds_script_execute
  debug:
    msg: "ds_script_execute: {{ ds_script_execute }}"
  when: ds_debug
