---
- name: Systemd service
  template:
    src: dsconfig.service.j2
    dest: /etc/systemd/system/ds-config.service
    owner: root
    group: root
    mode: 0755
  notify: systemctl-daemon-reload

- name: Enable and start service
  service:
    name: ds-config
    enabled: yes
    state: started
