---
- name: Check setup
  shell: "{{ ds_home_version }}/bin/status --offline || true"
  become: yes
  become_user: forgerock
  register: ds_status
  changed_when: False

- name: Setup fact
  set_fact:
    ds_setup: '{{ ds_status is search("The server has not been configured") }}'

- name: Setup
  command: "./setup directory-server {{ ds_setup_config|c2platform.forgerock.ds_cmd }}"
  args:
    chdir: "{{ ds_home_version }}"
  become: yes
  become_user: "{{ ds_owner }}"
  when:  ds_setup

- name: Stop DS
  command: "./stop-ds"
  args:
    chdir: "{{ ds_home_version }}/bin"
  become: yes
  become_user: "{{ ds_owner }}"
  when:  ds_setup

- name: Chown recursive
  file:
    dest: "{{ ds_home_version }}"
    owner: "{{ ds_owner }}"
    group: "{{ ds_group }}"
    recurse: yes

- name: Add pam limits # /etc/security/limits.conf
  pam_limits:
    domain: "{{ ds_owner }}"
    limit_type: "{{ item['limit_type'] }}"
    limit_item: nofile
    value: "{{ item['value'] }}"
  with_items:
    - limit_type: soft
      value: 65536
    - limit_type: hard
      value: 131072

- name: Create db schema ldifs
  copy:
    content: "{{ ds_db_schema_ldifs[item] }}"
    remote_src: yes
    dest: "{{ ds_home_version }}/db/schema/./{{ item }}.ldif"
    owner: "{{ ds_owner }}"
    group: "{{ ds_group }}"
    mode: '0640'
  with_items: "{{ ds_db_schema_ldifs }}"
  when: ds_db_schema_ldifs|default(False)
