---
- name: Check whether DS setup already run # noqa 305
  shell: "{{ ds_home }}/{{ ds_home|basename }}-{{ ds_version }}/bin/status --offline"
  register: ds_status
  ignore_errors: yes

- name: DS setup fact
  set_fact:
    ds_setup: '{{ ds_status is search("The server has not been configured") }}'

- name: Setup
  command: "./setup directory-server {{ ds_setup_config|c2platform.forgerock.ds_cmd }}"
  args:
    chdir: "{{ ds_home }}/{{ ds_home|basename }}-{{ ds_version }}"
  become: yes
  become_user: "{{ ds_owner }}"
  when:  ds_setup

- name: Stop DS
  command: "./stop-ds"
  args:
    chdir: "{{ ds_home }}/{{ ds_home|basename }}-{{ ds_version }}/bin"
  become: yes
  become_user: "{{ ds_owner }}"
  when:  ds_setup

- name: Chown recursive
  file:
    dest: "{{ ds_home }}/{{ ds_home|basename }}-{{ ds_version }}"
    owner: "{{ ds_owner }}"
    group: "{{ ds_group }}"
    recurse: yes

- name: Add pam limits # /etc/security/limits.conf
  pam_limits:
    domain: "{{ ds_owner }}"
    limit_type: "{{ item['limit_type'] }}"
    limit_item: nofile
    value: "{{ item['value'] }}"
  with_items:
    - limit_type: soft
      value: 65536
    - limit_type: hard
      value: 131072

