ig_service: "ig.service"

ig_version: 6.5.4
ig_home: /opt/ig


ig_versions:
  6.5.3:
    url: file:///vagrant/downloads/ig-6.5.3.zip
    checksum: "sha256: 933f97cabd60ac37073229729668461993c99db4f56ff7ad02eb055f663ecae8"

ig_owner: tomcat
ig_group: tomcat


tomcat_instance_dir: "/opt/{{tomcat_instance}}"
tomcat_instance: ig
