---
_ds_replication:
  connect_global:
    hostname: "{{ ds_replication['replication-server']['hostname'] }}"
    adminUid: "{{ ds_replication_global_admin }}"
    adminPassword: "{{ ds_replication_global_admin_password }}"
    port: "{{ ds_replication['replication-server']['port']|default(ds_connect['port']) }}"
    trustAll: ""
    no-prompt: ""
  connect_admin:
  connect_host1: "{{ ds_connect_ssl|combine({'hostname': ds_replication['host1']['hostname']|default(ds_connect['hostname'])}) }}"
  connect_host2: "{{ ds_connect_ssl|combine({'hostname': ds_replication['host2']['hostname']}) }}"
  configure:
    host1: "{{ ds_replication['host1']['hostname']|default(ds_connect['hostname']) }}"
    port1: "{{ ds_replication['host1']['port']|default(ds_connect['port']) }}"
    bindDn1: "{{ ds_replication['host1']['bindDN']|default(ds_connect['bindDN']) }}"
    bindPassword1: "{{ ds_replication['host1']['bindPassword']|default(ds_rootpw) }}"
    replicationPort1: "{{ ds_replication['host1']['replication_port']|default(ds_replication_port) }}"
    secureReplication1: ""
    host2: "{{ ds_replication['host2']['hostname'] }}"
    port2: "{{ ds_replication['host2']['port']|default(ds_connect['port']) }}"
    bindDn2: "{{ ds_replication['host2']['bindDN']|default(ds_connect['bindDN']) }}"
    bindPassword2: "{{ ds_replication['host2']['bindPassword']|default(ds_rootpw) }}"
    secureReplication2: ""
    replicationPort2: "{{ ds_replication['host2']['replication_port']|default(ds_replication_port) }}"
    baseDN: "{{ ds_replication['baseDNs'] }}"
    adminUid: "{{ ds_replication_global_admin }}"
    adminPassword: "{{ ds_replication_global_admin_password }}"
    trustAll: ""
    no-prompt: ""

_ds_replication_connect_admin: >
  {{ _ds_replication['replconnect']|combine(_ds_replication['connect_admin']) }}
