---
amster_version: 6.5.3
amster_home: /opt/amster

amster_ds_hostname: 1.1.1.51.nip.io
amster_ds_rootpw: supersecret
am_adminusrpw: FRdemo123
# The password that Amster sets for id AMadmin

amster_encryptpw: C2ITMXJ1I8BSp61bmJbp4oBaOjBDC6Xi


amster_versions:
  6.5.3:
    url: file:///vagrant/downloads/Amster-6.5.3.zip
    checksum: "sha256: 933f97cabd60ac37073229729668461993c99db4f56ff7ad02eb055f663ecae8"

amster_owner: tomcat
amster_group: tomcat

amster_download_dir: /tmp

amster_install_am:
  serverURL: 1.1.1.52.nip.io
  serveraddress: 1.1.1.52

amster_code_location: /vagrant/downloads

dsc_user_reports_inquire:
  hostname: "{{ amster_ds_hostname }}"
  port: 4444
  bindDN:  '"cn=Directory Manager"'
  bindPassword: "{{ amster_ds_rootpw }}"
  trustAll: ""
  useSsl: ""
  baseDn: '"cn=sa_reports,o=special,c=NL"'