---
amster_version: 6.5.3
amster_home: /opt/amster
amster_home_version: "{{ amster_home }}/{{ amster_home|basename }}-{{ amster_version }}"
amster_home_link: "{{ amster_home  }}/{{ amster_home|basename }}"

amster_ds_hostname: 1.1.1.51.nip.io
amster_ds_rootpw: supersecret
am_adminusrpw: FRdemo123
# The password that Amster sets for id AMadmin

amster_encryptpw: C2ITMXJ1I8BSp61bmJbp4oBaOjBDC6Xi

# TODO remove
am_home: /opt/am
am_version: 6.5.3

amster_versions:
  6.5.3:
    url: file:///vagrant/downloads/Amster-6.5.3.zip
    checksum: "sha256: 933f97cabd60ac37073229729668461993c99db4f56ff7ad02eb055f663ecae8"

amster_owner: tomcat
amster_group: tomcat

amster_download_dir: /tmp

amster_code_location: /vagrant/downloads

# These two to move to the PW vault mechanism chosen
amster_bindusrpwd: supersecret

dsc_user_reports_inquire:
  hostname: "{{ amster_ds_hostname }}"
  port: 4444
  bindDN: '"cn=Directory Manager"'
  bindPassword: "{{ amster_ds_rootpw }}"
  trustAll: ""
  useSsl: ""
  baseDn: '"cn=sa_reports,o=special,c=NL"'

amster_am_install:
  serverUrl: "http://{{ ansible_fqdn }}:8443/am"
  adminPwd: "{{ am_adminusrpw }}"
  acceptLicense: ''
  pwdEncKey: "{{ amster_encryptpw }}"
  cfgStoreDirMgr: "cn=Directory Manager"
  cfgStoreDirMgrPwd: '{{ ds_rootpw }}'
  cfgStore: dirServer
  cfgStoreHost: "{{ amster_ds_hostname }}"
  cfgStoreAdminPort: 4444
  cfgStoreSsl: SSL
  cfgStorePort: 10636
  cfgStoreRootSuffix: ou=am-config
  cookieDomain: "{{ ansible_fqdn }}"
  cfgDir: /opt/tomcat/am # default $HOME/openam
  userStoreDirMgr: "cn=Directory Manager"
  userStoreDirMgrPwd: "{{ ds_rootpw }}"
  userStoreHost: "{{ amster_ds_hostname  }}"
  userStoreType: LDAPv3ForOpenDS
  userStoreSsl: SSL
  userStorePort: 10636
  userStoreRootSuffix: dc=bkwi,dc=nl

amster_am_connect:
  private-key: /opt/tomcat/am/

amster_scripts:
  - 090-connect-to-openam
  - 100-installAM_1
  - 100-configure_AM
  - 101-connect_To_AM
  - 102-set-common-functions
  - 110-create-authentication-LdapTree
  - 110-function-create-authentication-tree
  - 110-function-delete-authentication-tree
  - 110-function-load-authentication-service
  - 111-configure-global-validation-service
  - 201-configure-SAML
  - 209-function_load_all_saml
  - 210-function-load-authentication-settings
  - 400-set-global-security-settings

amster_realm_defaults:
  backend: o=suwi,c=NL
  object_class: ["organizationalPerson","top","person","inetorgperson","suwinetPerson"]
  attributes: ["uid","givenName","objectClass","dn","cn","sn","mail","telephoneNumber","businessCategory","facsimileTelephoneNumber","description"]
  shared_secret: SBPSECRET # Looks like being the standard pw for accessing the DS server

amster_realms:
  uwv:
    fqdn: uwv.bto.suwinet.nl
    scripts:
      - 103-configure_realm
      - 107-update-identity-store
      - 108-set-sessionproperties
  suwinet:
    # object_class: ["organizationalPerson","top","person","inetorgperson","suwinetPerson"]
    # backend: o=suwi,c=NL
    # attributes: ["uid","givenName","objectClass","dn","cn","sn","mail","telephoneNumber","businessCategory","facsimileTelephoneNumber","description"]
    # shared_secret: SBPSECRET
    fqdn: suwinet.nl
    scripts:
      - 103-configure_realm
      - 104-create-J2EE_Agent
      - 105-create-policy-set
      - 106-create-policy
      - 107-update-identity-store
      - 108-set-sessionproperties
    j2ee_agent:
      name: suwinet-agent
      fqdn: suwinet-inkijk.bto.suwinet.nl
      fqdn_am: acs.bto.suwinet.nl
    policy:
      set_name: suwinet-policy-set
      name: suwinet-inkijk-policy
      resources:
        - http://inkijk.local:80/*
        - http://inkijk.local:80/*?
        - http://inkijk.local:80/*?*
      realms: ['uwv','suwinet']
      am_protected_uid_identifier: frankbtotest