---
ds_version: 6.5.4
ds_home: /opt/ds
ds_owner: forgerock
ds_group: forgerock

ds_versions:
  6.5.4:
    url: https://backstage.forgerock.com/downloads/
    checksum: "sha256: 820a197f4ac11b020c653ef00c684e63034df1f9f591b826ee4735c4bde7b8f1"
